name: log4cats
baseurl: /log4cats
description: Functional Logging
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 1.0.0+16-bc653be9+20190928-2239-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
